spring:
  application:
    name: admin_api
  config:
    import: optional:configserver:http://localhost:2222
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api4
  boot:
   admin:
     client:
       url: http://localhost:1111/

server:
  port: 7074