spring:
  application:
    name: orders_api
  config:
    import: optional:configserver:http://localhost:2222
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    rest:
      base-path: /api2
  boot:
   admin:
     client:
       url: http://localhost:1111/ 

server:
  port: 7072